<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="PREMCHAND" failures="1" tests="3" name="test1" time="12.978" errors="0" timestamp="2023-09-18T04:01:55 IST">
  <testcase classname="Tests.HomePage_Test" name="Verify_That_The_Ve3_global_Homepage_loads_successfully" time="0.266"/>
  <testcase classname="Tests.contact_test" name="Test_The_ContactFormByFillingItOutAndSubmittingItSuccessfully" time="12.561"/>
  <testcase classname="Tests.contact_test" name="AttemptToSubmitTheContactFormWithInvalidDataAndVerifyTheErrorMessages" time="0.051">
    <failure type="java.lang.AssertionError" message="Homepage is not opened expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Homepage is not opened expected [true] but found [false]
at pages.Homepage.HomePageURlOpened(Homepage.java:31)
at Tests.contact_test.AttemptToSubmitTheContactFormWithInvalidDataAndVerifyTheErrorMessages(contact_test.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- AttemptToSubmitTheContactFormWithInvalidDataAndVerifyTheErrorMessages -->
  <testcase classname="Tests.Base_tests" name="@BeforeSuite beforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
  <testcase classname="Tests.Base_tests" name="@AfterSuite afterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
</testsuite> <!-- test1 -->
